service: slack-notifications-lambda
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'sbx'}
  region: us-east-1
  role: ${env:AWS_ROLE}
  environment:
    SQS_SLACK_NOTIFICATIONS_QUEUE_URL: ${env:SQS_SLACK_NOTIFICATIONS_QUEUE_URL}
    SQS_SLACK_NOTIFICATIONS_DEAD_LETTER_QUEUE_URL: ${env:SQS_SLACK_NOTIFICATIONS_DEAD_LETTER_QUEUE_URL}
    SLACK_URL: ${env:SLACK_URL}
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-include-dependencies
functions:
  notificationHandler:
    handler: src/functions/notification-processor/notification-processor.notificationHandler
    events:
      - http:
          path: notificationHandler
          method: post
