service: slack-notifications-lambda
custom:
  stage: ${opt:stage, 'sbx'}
  environment: ${file(resources/env.yml):${self:custom.stage}, file(resources/env.yml):default}
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.stage}
  region: us-east-1
  role: ${self:custom.environment.aws.role}
  environment:
    sqsSlackNotificationsQueueUrl: ${self:custom.environment.sqs.slack_notifications_queue_url}
    slackUrl: ${self:custom.environment.slack.url}
resources:
  # - ${file(resources/sqs-queues.yml)}
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-include-dependencies
functions:
  notificationHandler:
    handler: src/functions/notification-processor/notification-processor.notificationHandler
    events:
      - http:
          path: notificationHandler
          method: post
